### ISSUE TITLE
Reduce command changes the provided filename

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail-wordpress-import#3]
It currently prepends all filenames with ``xml/``. This means you can't use any file outside that and it makes it a bit harder to select a file using autocomplete.

Wondering if we need this?

**Comment by nickmoreton** [comment]
Yes it saves it to the xml folder.

Do you mean keep the xml files at the root folder and not force to use a containing folder?

May be I should change any reference to a xml folder every where and then users can make their own choice about that.?

**Comment by kaedroho** [comment]
> Do you mean keep the xml files at the root folder and not force to use a containing folder?


Yep, I think if someone wants to use a file in the 'xml' folder, they should add 'xml' to the filename themselves. I think this would make the behaviour consistent with other command line apps and make it work with bash completion too.
