### ISSUE TITLE
Naming of management commands

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail-wordpress-import#4]
The management commands are currently named:

```
delete
discovery
reduce
runxml
```

These aren't very descriptive, wondering if we could rename them? Some suggestions:

 - ``delete_imported_pages``
 - ``extract_xml_mapping``
 - ``reduce_xml``
 -  ``import_xml``

What do you think?

**Comment by nickmoreton** [comment]
> Implemented in: [PR](https://github.com/nickmoreton/wagtail-xmlimport/pull/10)
