### ISSUE TITLE
runxml returns LookupError: No installed app with label 'pages'

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail-wordpress-import#5]
Sounds like something needs to be made configurable. If it's not configured properly, an ``ImproperlyConfigured`` error should be raised.

**Comment by nickmoreton** [comment]
Implemented in [PR](https://github.com/nickmoreton/wagtail-xmlimport/pull/10/commits/f26e536632bbe48888010f489e64bb5df3e90bce)
