### ISSUE TITLE
Typo in runxml

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail-wordpress-import#6]
This line looks like it will crash if run since ``ERROR()`` takes a string and returns a string:

https://github.com/nickmoreton/wagtail-xmlimport/blob/d82e5902101ccba3c7a8f5f2031c9ce3f038ebde/wagtail_xmlimport/management/commands/runxml.py#L43

**Comment by nickmoreton** [comment]
> Implemented in: [PR](https://github.com/nickmoreton/wagtail-xmlimport/pull/10/commits/82ae2fdbb9063ff7cde49bbd8af2227deb8905e3)
