### ISSUE TITLE
What does this line do?

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail-wordpress-import#7]
https://github.com/nickmoreton/wagtail-xmlimport/blob/d82e5902101ccba3c7a8f5f2031c9ce3f038ebde/wagtail_xmlimport/management/commands/runxml.py#L39

**Comment by nickmoreton** [comment]
It's to set True of False in the console at the end of the script.

e.g.

Summary ========================
Imported: 3042 Skipped: 4461 Processed: 7503
Check: True

Checking if all the items we processed have been imported if they can be

**Comment by nickmoreton** [comment]
Fixed in https://github.com/torchbox/wagtail-wordpress-import/pull/31
