### ISSUE TITLE
Should we use an id for the parent?

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail-wordpress-import#8]
Currently ``Importer.run()`` takes an app/model combination for the parent page. It finds the parent page by getting the first instance of this model.

Many sites have multiple homepages, so should we use something more specific, such as a slug or the page id?

**Comment by nickmoreton** [comment]
Good point

> Implemented in: [PR](https://github.com/nickmoreton/wagtail-xmlimport/pull/10/commits/6b0a5ee1139bbf09d1434134e3bcb05f0058cf8f)
